var headerList="H1 H2 H3 H4 H5 H6".split(" "),blockElements="INS DEL P DIV H1 H2 H3 H4 H5 H6 BLOCKQUOTE PRE TABLE DL OL UL ADDRESS SCRIPT NOSCRIPT FORM FIELDSET IFRAME MATH IMG OBJECT EMBED HR".split(" "),headers=[],visible=[],iconThis="←",iconAll="↕",headerLinks=" <button class='this' title='Collapse this section'>"+iconThis+"</button> <button class='all' title='Collapse all sections at this level'>"+iconAll+"</button>",keyNext=106,keyPrev=107,keyNextUp=108,keyPrevUp=
105,keyFirst=117,keyLast=109,keyAll=97,keyExpand=102,keyTheme=115,helpBoxText="<h3>Keyboard shortcuts</h3><ul><li><b>"+String.fromCharCode(keyNext)+"</b>: Next section</li><li><b>"+String.fromCharCode(keyPrev)+"</b>: Previous section</li><li><b>return/enter</b>: Toggle active section</li><li><b>"+String.fromCharCode(keyNextUp)+"</b>: Next section up</li><li><b>"+String.fromCharCode(keyPrevUp)+"</b>: Previous section up</li><li><b>"+String.fromCharCode(keyFirst)+"</b>: First section</li><li><b>"+String.fromCharCode(keyLast)+
"</b>: Last section</li><li><b>"+String.fromCharCode(keyAll)+"</b>: Toggle active section and all sections at the same level</li><li><b>"+String.fromCharCode(keyExpand)+"</b>: Expand all sections (do this before you search within the document!)</li><li><b>"+String.fromCharCode(keyTheme)+"</b>: Switch theme (light/dark)</li></ul>";
window.onload=function(){document.documentElement.classList.add("light");headers=getElements(headerList,!1);for(var a=0;a<headers.length;a++)headers[a].innerHTML+=headerLinks,headers[a].onclick=toggleHandler;makeActive(headers[0]);for(var a=document.getElementsByTagName("*"),b,c=0;c<a.length;c++)if("BODY"===a[c].tagName){b=a[c+1];break}a=document.createElement("div");a.classList.add("js-infobox");document.body.insertBefore(a,b);a.innerHTML=helpBoxText};
window.onkeypress=function(a){a=a||window.event;a=a.which||a.keyCode;if(0===visible.length)visible=getElements(headerList,!0);else if(13===a)toggleHandler(whoIsActive());else if(a===keyAll){var b=document.getElementsByClassName("active")[0].tagName,b=document.getElementsByTagName(b);toggleHandler(b)}if(a===keyNext)for(a=0;a<visible.length-1;a++){if(visible[a].classList.contains("active")){clearActive(visible);makeActive(visible[a+1]);break}}else if(a===keyPrev)for(a=visible.length-1;0<a;a--){if(visible[a].classList.contains("active")){clearActive(visible);
makeActive(visible[a-1]);break}}else if(a===keyFirst)clearActive(visible),makeActive(visible[0]);else if(a===keyLast)clearActive(visible),makeActive(visible[visible.length-1]);else if(a===keyPrevUp)for(a=0;a<visible.length;a++){if(visible[a]===whoIsActive())for(b=a-1;0<=b;b--)if(getHeaderNum(whoIsActive())>getHeaderNum(visible[b])){clearActive(visible);makeActive(visible[b]);break}}else if(a===keyNextUp)for(a=0;a<visible.length;a++){if(visible[a]===whoIsActive())for(b=a+1;b<visible.length;b++)if(getHeaderNum(whoIsActive())>
getHeaderNum(visible[b])){clearActive(visible);makeActive(visible[b]);break}}else if(a===keyExpand){for(a=whoIsActive();isAnythingHidden(headers);)for(b=0;b<headers.length;b++)headers[b].classList.contains("collapsed")&&toggleHandler(headers[b]);clearActive(visible);makeActive(a)}else a===keyTheme&&(a=document.documentElement,a.classList.contains("light")?(a.classList.remove("light"),a.classList.add("dark")):(a.classList.remove("dark"),a.classList.add("light")))};
function toggleHandler(a){var b=getTargets(a);if(void 0===b.length)toggleMe(b);else for(var c=0;c<b.length;c++)toggleMe(b[c]);c=whoIsActive();clearActive(headers);void 0===b.length?makeActive(b):isClick(a)?makeActive(a.target.parentElement):makeActive(c);visible=getElements(headerList,!0)}
function toggleMe(a){for(var b=getHeaderNum(a),c=getElements(blockElements,!1),d=0;d<c.length;d++)if(c[d]===a){b=compareHeaders(d,c,b);if(isCollapsed(a)){removeCollapsedClass(a);for(d+=1;c[d]!==b&&void 0!==c[d];){var e=c[d].tagName;if("H1"===e||"H2"===e||"H3"===e||"H4"===e||"H5"===e||"H6"===e)if(isCollapsed(c[d])){e=getHeaderNum(c[d]);e=compareHeaders(d,c,e);for(c[d].classList.remove("hidden");c[d]!==e&&void 0!==c[d];)d++}else c[d].classList.remove("hidden"),d++;else c[d].classList.remove("hidden"),
d++}}else{addCollapsedClass(a);for(d+=1;c[d]!==b&&void 0!==c[d];)c[d].classList.add("hidden"),d++}addToggler(a);break}}function getElements(a,b){for(var c=document.getElementsByTagName("*"),d=0,e=[],f=0;f<c.length;f++)for(var g=0;g<a.length;g++)c[f].tagName===a[g]&&!c[f].parentElement.classList.contains("js-infobox")&&(b?c[f].classList.contains("hidden")||(e[d]=c[f],d++):(e[d]=c[f],d++));return e}
function compareHeaders(a,b,c){for(a+=1;a<b.length;a++){if(a===b.length-1)return b=getElements(blockElements,!1),b[b.length];for(var d=0;d<headerList.length;d++)if(b[a].tagName===headerList[d]&&b[a].tagName.slice(1)<=c)return b[a]}}
function getTargets(a){if(isClick(a)){for(var b=0,c=0;c<headerList.length;c++)a.target.tagName===headerList[c]&&(b=1);return 1===b?a.target:a.target.classList.contains("all")?document.getElementsByTagName(a.target.parentElement.tagName):a.target.parentElement}return a}function addToggler(a){a.onclick=toggleHandler}function isCollapsed(a){return a.classList.contains("collapsed")}function removeCollapsedClass(a){a.classList.remove("collapsed")}
function addCollapsedClass(a){a.classList.add("collapsed")}function getHeaderNum(a){return void 0===a.length?a.tagName.slice(1):a[0].tagName.slice(1)}function makeActive(a){a.classList.add("active");a.scrollIntoView()}function clearActive(a){for(var b=0;b<a.length;b++)a[b].classList.contains("active")&&a[b].classList.remove("active")}function isClick(a){if(void 0!==a.target)return!0}function whoIsActive(){return document.getElementsByClassName("active")[0]}
function isAnythingHidden(a){if(void 0===a.length)return a.classList.contains("collapsed");for(var b=0,c=0;c<a.length;c++)a[c].classList.contains("collapsed")&&b++;return 0<b?!0:!1};
